version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: zpinto/hackhoot-frontend:latest
    ports:
      - 80:80

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: zpinto/hackhoot-api:latest
    ports:
      - 5000:5000

  db:
    image: mongo
    volumes:
      - kahoot-data:/data/db

volumes:
  kahoot-data:
